runtime: python27
api_version: 1
threadsafe: true
env_variables:

libraries:
- name: ssl
  version: latest

handlers:
- url: /
  static_files: site/index.html
  upload: site/index.html
- url: /favicon.ico
  static_files: site/favicon.ico
  upload: site/favicon.ico
- url: /privacy_policy.html
  static_files: site/privacy_policy.html
  upload: site/privacy_policy.html
- url: /images/appscreen.png
  static_files: site/images/appscreen.png
  upload: site/images/appscreen.png
- url: /taxonomy.html
  static_files: site/taxonomy.html
  upload: site/taxonomy.html
- url: /birds.json
  static_files: site/birds.json
  upload: site/birds.json
- url: /regenerate_json
  script: scripts.regenerate_json_web.app
  login: admin
