application: nerdbirder
version: 1
runtime: python27
api_version: 1
threadsafe: true
env_variables:

handlers:
- url: /
  static_files: site/index.html
  upload: site/index.html
- url: /birds.json
  static_files: site/birds.json
  upload: site/birds.json
- url: /regenerate
  script: scripts.app
  login: admin
